name: structExpectations-development

channels:
  - defaults
  - conda-forge
  - OpenSourceEconomics

dependencies:
  - pip
  - codecov
  - estimagic
  - matplotlib
  - numba
  - pandas
  - pyaml
  - numpy
  - nlopt
  - pytest
  - pytest-cov
  - Sphinx
  - flake8
  - sphinx-autobuild
  - jupyterlab
  - pip:
    - Py-BOBYQA
    - black
    - pre-commit
    - PyPDF2
