name: dev_soepy

channels:
  - conda
  - conda-forge

dependencies:
  - python=3.6
  - numpy
  - pandas
  - statsmodels
  - pytest
  - pytest-xdist
  - scipy
  - flake8
  - jupyterlab
  - pip:
    - oyaml
